import { ExpenseCategory } from "../types";

const CATEGORY_KEYWORDS: Record<ExpenseCategory, string[]> = {
  food: [
    "carrefour",
    "pao de acucar",
    "pão de açúcar",
    "assai",
    "muffato",
    "zona sul",
    "babaçu",
    "preunic",
    "guanabara",
    "mundial",
    "comper",
    "b超市",
    "zaffari",
    "supermercado",
    "hipermercado",
    "atacadao",
    "atacadão",
    "hortifruti",
    "sacolao",
    "sacolão",
    "mercearia",
    "padaria",
    "panificadora",
  ],
  eating_out: [
    "ifood",
    "mcdonalds",
    "mc donalds",
    "subway",
    "burger king",
    "bk ",
    "starbucks",
    "habibs",
    "spoleto",
    "outback",
    "madeiro",
    "ragazzo",
    "bacio di latte",
    "restaurante",
    "pizzaria",
    "churrascaria",
    "lanchonete",
    "bar ",
    "cafe ",
    "café",
    "doceria",
    "sorvete",
  ],
  clothing: [
    "zara",
    "shein",
    "shopee",
    "aliexpress",
    "ali *",
    "renner",
    "riachuelo",
    "cea ",
    "c&a",
    "marisa",
    "centauro",
    "decathlon",
    "arezzo",
    "havainas",
    "loja de roupa",
    "vestuario",
    "calçados",
    "tenis",
  ],
  transport: [
    "uber",
    "99app",
    "99 taxi",
    "indrive",
    "posto",
    "ipiranga",
    "petrobras",
    "shell",
    "sem parar",
    "veloe",
    "taggy",
    "pedagio",
    "pedágio",
    "metro",
    "metrô",
    "cptm",
    "rodoviaria",
    "passagem",
    "latam",
    "azul linha",
    "gol ",
  ],
  investment: [
    "tesouro direto",
    "nu invest",
    "xp investimentos",
    "rico",
    "inter dtvm",
    "btg pactual",
    "cdi",
    "ações",
    "fii",
    "binance",
    "cripto",
    "corretora",
  ],
  others: [
    "netflix",
    "spotify",
    "amazon prime",
    "disneyplus",
    "hbo",
    "crunchyroll",
    "claro",
    "vivo",
    "tim ",
    "oi fibra",
    "sabesp",
    "enel",
    "light ",
    "comgás",
    "mercado livre",
    "mercadolivre",
    "magalu",
    "magazine luiza",
    "casas bahia",
    "americanas",
    "farmacia",
    "droga",
    "raia",
    "drogasil",
    "pague menos",
  ],
};

/**
 * @param description
 */
export function classifyExpense(description: string): ExpenseCategory {
  const cleanDescription = description.toLowerCase().trim();

  for (const [category, keywords] of Object.entries(CATEGORY_KEYWORDS)) {
    const hasMatch = keywords.some((keyword) =>
      cleanDescription.includes(keyword.toLowerCase()),
    );

    if (hasMatch) {
      return category as ExpenseCategory;
    }
  }

  return "others";
}
